name: Deployment

on:
    push:
        branches:
            - main

permissions:
    contents: read
    pages: write
    id-token: write

concurrency:
    group: 'pages'
    cancel-in-progress: true

jobs:
    deploy:
        name: Deploy
        runs-on: ubuntu-latest
        environment:
            name: github-pages
            url: ${{ steps.deployment.outputs.page_url }}
        steps:
            -   name: Checkout code
                uses: actions/checkout@v4.1.1
            -   name: Setup NodeJS
                uses: actions/setup-node@v4.0.1
                with:
                    node-version: 18
            -   name: Install dependencies
                run: npm install
            -   name: Build website
                run: npm run build
            -   name: Setup GitHub-Pages
                uses: actions/configure-pages@v4.0.0
            -   name: Upload artifacts
                uses: actions/upload-pages-artifact@v4.0.0
                with:
                    path: './build'
            -   name: Deploy to GitHub-Pages
                uses: actions/deploy-pages@v4.0.2
                id: deployment
